modLoader="kotlinforforge" #mandatory
loaderVersion="[5.3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Sreeraj-S/PokemonToItem/issues"

[[mods]] #mandatory
modId="pokemontoitem" #mandatory
version="${version}" #mandatory
displayName="Pokemon To Item" #mandatory
displayURL="https://github.com/Sreeraj-S"
#logoFile="examplemod.png" #optional
credits="Thanks to the Cobblemon Community."
authors="Sreeraj"
description='''
 Adds special commands to pokemontoitem
'''

[[dependencies.pokemontoitem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21]"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokemontoitem]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokemontoitem]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "NONE"
side = "BOTH"
